<?php
/**
 * CardTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * openHAB REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.15
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CardTest Class Doc Comment
 *
 * @category    Class
 * @description Card
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CardTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Card"
     */
    public function testCard()
    {
    }

    /**
     * Test attribute "config"
     */
    public function testPropertyConfig()
    {
    }

    /**
     * Test attribute "slots"
     */
    public function testPropertySlots()
    {
    }

    /**
     * Test attribute "uid"
     */
    public function testPropertyUid()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "subtitle"
     */
    public function testPropertySubtitle()
    {
    }

    /**
     * Test attribute "tags"
     */
    public function testPropertyTags()
    {
    }

    /**
     * Test attribute "bookmarked"
     */
    public function testPropertyBookmarked()
    {
    }

    /**
     * Test attribute "not_reuseable_in_chat"
     */
    public function testPropertyNotReuseableInChat()
    {
    }

    /**
     * Test attribute "add_to_deck_denied"
     */
    public function testPropertyAddToDeckDenied()
    {
    }

    /**
     * Test attribute "ephemeral"
     */
    public function testPropertyEphemeral()
    {
    }

    /**
     * Test attribute "timestamp"
     */
    public function testPropertyTimestamp()
    {
    }

    /**
     * Test attribute "object_attributes"
     */
    public function testPropertyObjectAttributes()
    {
    }

    /**
     * Test attribute "location_attributes"
     */
    public function testPropertyLocationAttributes()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }
}
