<?php
/**
 * ThingUIDTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * openHAB REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.15
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ThingUIDTest Class Doc Comment
 *
 * @category    Class
 * @description ThingUID
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ThingUIDTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ThingUID"
     */
    public function testThingUID()
    {
    }

    /**
     * Test attribute "thing_type_id"
     */
    public function testPropertyThingTypeId()
    {
    }

    /**
     * Test attribute "bridge_ids"
     */
    public function testPropertyBridgeIds()
    {
    }

    /**
     * Test attribute "thing_type_uid"
     */
    public function testPropertyThingTypeUid()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "binding_id"
     */
    public function testPropertyBindingId()
    {
    }

    /**
     * Test attribute "as_string"
     */
    public function testPropertyAsString()
    {
    }
}
