<?php
/**
 * InboxApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * openHAB REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.15
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * InboxApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class InboxApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for approve
     *
     * Approves the discovery result by adding the thing to the registry..
     *
     */
    public function testApprove()
    {
    }

    /**
     * Test case for delete
     *
     * Removes the discovery result from the inbox..
     *
     */
    public function testDelete()
    {
    }

    /**
     * Test case for getAll
     *
     * Get all discovered things..
     *
     */
    public function testGetAll()
    {
    }

    /**
     * Test case for ignore
     *
     * Flags a discovery result as ignored for further processing..
     *
     */
    public function testIgnore()
    {
    }

    /**
     * Test case for unignore
     *
     * Removes ignore flag from a discovery result..
     *
     */
    public function testUnignore()
    {
    }
}
