<?php
/**
 * ItemsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * openHAB REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.15
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * ItemsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ItemsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addMember
     *
     * Adds a new member to a group item..
     *
     */
    public function testAddMember()
    {
    }

    /**
     * Test case for addMetadata
     *
     * Adds metadata to an item..
     *
     */
    public function testAddMetadata()
    {
    }

    /**
     * Test case for addTag
     *
     * Adds a tag to an item..
     *
     */
    public function testAddTag()
    {
    }

    /**
     * Test case for createOrUpdateItem
     *
     * Adds a new item to the registry or updates the existing item..
     *
     */
    public function testCreateOrUpdateItem()
    {
    }

    /**
     * Test case for createOrUpdateItems
     *
     * Adds a list of items to the registry or updates the existing items..
     *
     */
    public function testCreateOrUpdateItems()
    {
    }

    /**
     * Test case for getItemData
     *
     * Gets a single item..
     *
     */
    public function testGetItemData()
    {
    }

    /**
     * Test case for getItems
     *
     * Get all available items..
     *
     */
    public function testGetItems()
    {
    }

    /**
     * Test case for getPlainItemState
     *
     * Gets the state of an item..
     *
     */
    public function testGetPlainItemState()
    {
    }

    /**
     * Test case for postItemCommand
     *
     * Sends a command to an item..
     *
     */
    public function testPostItemCommand()
    {
    }

    /**
     * Test case for putItemState
     *
     * Updates the state of an item..
     *
     */
    public function testPutItemState()
    {
    }

    /**
     * Test case for removeItem
     *
     * Removes an item from the registry..
     *
     */
    public function testRemoveItem()
    {
    }

    /**
     * Test case for removeMember
     *
     * Removes an existing member from a group item..
     *
     */
    public function testRemoveMember()
    {
    }

    /**
     * Test case for removeMetadata
     *
     * Removes metadata from an item..
     *
     */
    public function testRemoveMetadata()
    {
    }

    /**
     * Test case for removeTag
     *
     * Removes a tag from an item..
     *
     */
    public function testRemoveTag()
    {
    }
}
