<?php
/**
 * ServicesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * openHAB REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.15
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * ServicesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ServicesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteConfiguration
     *
     * Deletes a service configuration for given service ID and returns the old configuration..
     *
     */
    public function testDeleteConfiguration()
    {
    }

    /**
     * Test case for getAll
     *
     * Get all configurable services..
     *
     */
    public function testGetAll()
    {
    }

    /**
     * Test case for getById
     *
     * Get configurable service for given service ID..
     *
     */
    public function testGetById()
    {
    }

    /**
     * Test case for getConfiguration
     *
     * Get service configuration for given service ID..
     *
     */
    public function testGetConfiguration()
    {
    }

    /**
     * Test case for getMultiConfigServicesByFactoryPid
     *
     * Get existing multiple context service configurations for the given factory PID..
     *
     */
    public function testGetMultiConfigServicesByFactoryPid()
    {
    }

    /**
     * Test case for updateConfiguration
     *
     * Updates a service configuration for given service ID and returns the old configuration..
     *
     */
    public function testUpdateConfiguration()
    {
    }
}
