<?php
/**
 * SitemapsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * openHAB REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.15
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * SitemapsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SitemapsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createEventSubscription
     *
     * Creates a sitemap event subscription..
     *
     */
    public function testCreateEventSubscription()
    {
    }

    /**
     * Test case for getPageData
     *
     * Polls the data for a sitemap..
     *
     */
    public function testGetPageData()
    {
    }

    /**
     * Test case for getSitemapData
     *
     * Get sitemap by name..
     *
     */
    public function testGetSitemapData()
    {
    }

    /**
     * Test case for getSitemapEvents
     *
     * Get sitemap events..
     *
     */
    public function testGetSitemapEvents()
    {
    }

    /**
     * Test case for getSitemaps
     *
     * Get all available sitemaps..
     *
     */
    public function testGetSitemaps()
    {
    }
}
