<?php
/**
 * ThingsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * openHAB REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.15
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * ThingsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ThingsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for create
     *
     * Creates a new thing and adds it to the registry..
     *
     */
    public function testCreate()
    {
    }

    /**
     * Test case for getAll
     *
     * Get all available things..
     *
     */
    public function testGetAll()
    {
    }

    /**
     * Test case for getByUID
     *
     * Gets thing by UID..
     *
     */
    public function testGetByUID()
    {
    }

    /**
     * Test case for getConfigStatus
     *
     * Gets thing's config status..
     *
     */
    public function testGetConfigStatus()
    {
    }

    /**
     * Test case for getFirmwareStatus
     *
     * Gets thing's firmware status..
     *
     */
    public function testGetFirmwareStatus()
    {
    }

    /**
     * Test case for getFirmwares
     *
     * Get all available firmwares for provided thing UID.
     *
     */
    public function testGetFirmwares()
    {
    }

    /**
     * Test case for getStatus
     *
     * Gets thing's status..
     *
     */
    public function testGetStatus()
    {
    }

    /**
     * Test case for remove
     *
     * Removes a thing from the registry. Set 'force' to __true__ if you want the thing te be removed immediately..
     *
     */
    public function testRemove()
    {
    }

    /**
     * Test case for setEnabled
     *
     * Sets the thing enabled status..
     *
     */
    public function testSetEnabled()
    {
    }

    /**
     * Test case for update
     *
     * Updates a thing..
     *
     */
    public function testUpdate()
    {
    }

    /**
     * Test case for updateConfiguration
     *
     * Updates thing's configuration..
     *
     */
    public function testUpdateConfiguration()
    {
    }

    /**
     * Test case for updateFirmware
     *
     * Update thing firmware..
     *
     */
    public function testUpdateFirmware()
    {
    }
}
